id: P001836
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W27410
  title: ནོར་གཟུངས་ཆེན་མོའི་མདོ
  author: ''
  volumes:
    faaac45981ea46d789784a681a9cba5d:
      image_group_id: I4327
      title: ''
      volume_number: 1
      total_pages: 362
      base_file: v001.txt
